# Generated by Django 3.2.7 on 2021-09-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company_operation.basemodel')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            bases=('company_operation.basemodel',),
        ),
        migrations.CreateModel(
            name='OperationStatus',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company_operation.basemodel')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            bases=('company_operation.basemodel',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company_operation.basemodel')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
            bases=('company_operation.basemodel',),
        ),
    ]
